#!/command/with-contenv sh

echo "[cont-init.d] NFS kernel server deshabilitado temporalmente"
exit 0

# DESHABILITADO TEMPORALMENTE
# echo "[cont-init.d] Iniciando NFS kernel server..."
# 
# # Asegurar que /etc/exports existe
# if [ ! -f /etc/exports ]; then
#     echo "[cont-init.d] ADVERTENCIA: /etc/exports no existe"
#     touch /etc/exports
# fi
# 
# # Crear directorio para locks si no existe
# mkdir -p /var/lib/nfs/v4recovery
# 
# # Iniciar servidor NFS
# /etc/init.d/nfs-kernel-server start
# 
# # Verificar que el servidor está corriendo
# for i in 1 2 3 4 5; do
#     if rpcinfo -p | grep -q nfs; then
#         echo "[cont-init.d] NFS kernel server iniciado correctamente"
#         # Exportar shares
#         exportfs -ra
#         exit 0
#     fi
#     echo "[cont-init.d] Esperando NFS server... intento $i/5"
#     sleep 2
# done
# 
# echo "[cont-init.d] ADVERTENCIA: NFS server puede no estar funcionando correctamente"
